In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore") 

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [3]:
df = pd.read_csv(r'Z:\DS DATA\modeldf.csv')
df.shape

(404290, 29)

In [4]:
df =df.sample(n=10000,random_state=0)
print(df.shape)
df.head()

(10000, 29)


is_duplicate  freq_qid1  freq_qid2  q1_alphabit_len  q2_alphabit_len  \
187265             1         22         10               23               43   
6557               1          1          1               37               46   
139264             0          1          1               72               61   
240135             1          3          1               69               44   
3336               1         12         12               51               31   

        q1_n_unique_words  q2_n_unique_words  q1_union_q2  q1_intersec_q2  \
187265                  6                 10         13.0             6.0   
6557                    7                  8          9.0             7.0   
139264                 12                 10         18.0            12.0   
240135                  9                  7         11.0             9.0   
3336                    9                  6         12.0             9.0   

        total_unique_words  ...   ctc_min   ctc_max  fw_com  lw_com  abs_diff  \
187265                16.0  ...  0.499992  0.299997     0.0     0.0       4.0   
6557                  15.0  ...  0.857131  0.749991     1.0     0.0       1.0   
139264                22.0  ...  0.363633  0.285712     1.0     0.0       3.0   
240135                16.0  ...  0.714276  0.555549     1.0     0.0       2.0   
3336                  15.0  ...  0.499992  0.299997     0.0     1.0       4.0   

        ratio  token_set_ratio  token_sort_ratio  fuzz_ratio  partial_ratio  
187265    8.0               65                45          36             52  
6557      7.5               88                80          70             68  
139264   12.5               64                56          35             38  
240135    8.0               87                66          71             86  
3336      8.0               76                62          63             65  

[5 rows x 29 columns]

In [5]:
y=df["is_duplicate"]
x=df.drop(columns=["is_duplicate"])
print(y.shape,x.shape)

(10000,) (10000, 28)


In [6]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=0,test_size=0.30)
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(7000, 28) (3000, 28) (7000,) (3000,)


<h2>Building a random Model (Finding Worest-case LogLoss)</h2>

In [11]:
test_len = len(y_test)
predicted_y = np.zeros((test_len,2))
print(predicted_y)
print("-"*100)
for i in range(test_len):
    rand_probs = np.random.rand(1,2)
    predicted_y[i] = ((rand_probs/sum(sum(rand_probs)))[0])
    print(predicted_y)
# print("Log loss on Test Data using Random Model",log_loss(y_test, predicted_y, eps=1e-15))


[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]]
----------------------------------------------------------------------------------------------------
[[0.07893448 0.92106552]
 [0.         0.        ]
 [0.         0.        ]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.         0.        ]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998

[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0

[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0

 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 

[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0

[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0

[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0

[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0

[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0

[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0.21001537]
 ...
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]]
[[0.07893448 0.92106552]
 [0.82318779 0.17681221]
 [0.78998463 0

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report
cm = confusion_matrix(y_test,y_pred)

pd.DataFrame(cm,columns=sorted(y.unique()),index=sorted(y.unique()))

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report
knn = KNeighborsClassifier(n_neighbors=7)
knn.fit(XX_train,YY_train)
pred = knn.predict(x_test)
acc = accuracy_score(y_test,pred,normalize=True)*float(100)
print("\n****Test accuracy for k = 3 is %d%%" % (acc))

y_pred=nei.predict(x_test)
print(classification_report(y_test,pred))


In [170]:
kneibhour = KNeighborsClassifier(n_neighbors=97)
kneibhour.fit(x_train,y_train)
score = kneibhour.score(x_test,y_test)*100

In [171]:
print(score)

75.8


In [121]:
from sklearn.linear_model import LogisticRegression

In [122]:
LgReg = LogisticRegression()
LgReg.fit(x_train,y_train)
print(LgReg.predict(x_test)[:20])
print(np.array(y_test[:20]))

[0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 1 0]
[1 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0]


In [123]:
score = LgReg.score(x_test,y_test)*100
print(score)

76.6
