In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import log_loss,accuracy_score,classification_report,confusion_matrix

In [30]:
# Pulling Data  from csv file
df = pd.read_csv(r'Z:\DS DATA\modeldf.csv')
df.shape

(404290, 29)

In [31]:
# Picking some random sample to quick up the process

df= df.sample(n=10000,random_state=0)
print(df.shape)
df.head()

(10000, 29)


is_duplicate  freq_qid1  freq_qid2  q1_alphabit_len  q2_alphabit_len  \
187265             1         22         10               23               43   
6557               1          1          1               37               46   
139264             0          1          1               72               61   
240135             1          3          1               69               44   
3336               1         12         12               51               31   

        q1_n_unique_words  q2_n_unique_words  q1_union_q2  q1_intersec_q2  \
187265                  6                 10         13.0             6.0   
6557                    7                  8          9.0             7.0   
139264                 12                 10         18.0            12.0   
240135                  9                  7         11.0             9.0   
3336                    9                  6         12.0             9.0   

        total_unique_words  ...   ctc_min   ctc_max  fw_com  lw_com  abs_diff  \
187265                16.0  ...  0.499992  0.299997     0.0     0.0       4.0   
6557                  15.0  ...  0.857131  0.749991     1.0     0.0       1.0   
139264                22.0  ...  0.363633  0.285712     1.0     0.0       3.0   
240135                16.0  ...  0.714276  0.555549     1.0     0.0       2.0   
3336                  15.0  ...  0.499992  0.299997     0.0     1.0       4.0   

        ratio  token_set_ratio  token_sort_ratio  fuzz_ratio  partial_ratio  
187265    8.0               65                45          36             52  
6557      7.5               88                80          70             68  
139264   12.5               64                56          35             38  
240135    8.0               87                66          71             86  
3336      8.0               76                62          63             65  

[5 rows x 29 columns]

In [32]:
# extracting the target column from feature columns

y=df['is_duplicate']
x=df.drop(columns=["is_duplicate"])
print("Shape of X: (Feature columns)",x.shape)
print("Shape of Y: (Target columns)",y.shape)


Shape of X: (Feature columns) (10000, 28)
Shape of Y: (Target columns) (10000,)


In [33]:
# 79641     1
# y_true= list(map(int,y.values))
# print(type(y_true))

In [34]:
# splitting data set for train and test

x_train,x_test,y_train,y_test = train_test_split(
    x, y, stratify=y,random_state=0, test_size=0.3)
print("Shape of x_train: (Training Data)",x_train.shape)
print("Shape of x_test: (Testing Data)",x_test.shape)


Shape of x_train: (Training Data) (7000, 28)
Shape of x_test: (Testing Data) (3000, 28)


<h1>Building a random model to calculate the worest-case of log_loss</h1>

In [35]:
# this is line creates an ndarray of shape 3000x2 
predicted_y = np.zeros((len(y_test),2))
print(predicted_y)

            # OUTPUT
# [[0. 0.]
#  [0. 0.]
#  [0. 0.]
#  ...
#  [0. 0.]
#  [0. 0.]
#  [0. 0.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [36]:
for i in range(len(y_test)):
#     this is line will create a array 1X2 
#     with random distribution populated in it
    rand_probs = np.random.rand(1,2)
    predicted_y[i]= ((rand_probs/sum(sum(rand_probs)))[0])
print(log_loss(y_test,predicted_y,eps=1e-15))


0.8715618249313896


In [37]:
x =np.argmax(predicted_y, axis=1)
print(x)

[0 1 0 ... 0 0 0]


In [38]:
log_loss(["spam", "ham", "ham", "spam"],[[.1, .9], [.9, .1], [.8, .2], [.35, .65]])

0.21616187468057912

In [39]:
y_true = [2, 0, 2, 2, 0, 1]
y_pred = [0, 0, 2, 2, 0, 2]
confusion_matrix(y_true, y_pred)
# array([[2, 0, 0],
#        [0, 0, 1],
#        [1, 0, 2]])

a=np.arange(5)
print(a<=3)

[ True  True  True  True False]
